language: python

python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1

install: python setup.py develop

#script: python setup.py test
script: django-admin.py test ajaxutils_tests --settings=ajaxutils_tests.settings

notifications:
  irc:
    channels: "irc.freenode.org#ahref"
    on_success: change
    on_failure: change
